export interface StockEntry {
  symbol: string;
  name: string;
}

// NSE F&O + major listed stocks
export const NSE_STOCKS: StockEntry[] = [
  { symbol: 'AARTIIND', name: 'Aarti Industries' },
  { symbol: 'ABB', name: 'ABB India' },
  { symbol: 'ABCAPITAL', name: 'Aditya Birla Capital' },
  { symbol: 'ABFRL', name: 'Aditya Birla Fashion & Retail' },
  { symbol: 'ACC', name: 'ACC Ltd' },
  { symbol: 'ADANIENSOL', name: 'Adani Energy Solutions' },
  { symbol: 'ADANIENT', name: 'Adani Enterprises' },
  { symbol: 'ADANIGREEN', name: 'Adani Green Energy' },
  { symbol: 'ADANIPORTS', name: 'Adani Ports & SEZ' },
  { symbol: 'ADANIPOWER', name: 'Adani Power' },
  { symbol: 'ALKEM', name: 'Alkem Laboratories' },
  { symbol: 'AMBUJACEM', name: 'Ambuja Cements' },
  { symbol: 'ANGELONE', name: 'Angel One' },
  { symbol: 'APOLLOHOSP', name: 'Apollo Hospitals Enterprise' },
  { symbol: 'APOLLOTYRE', name: 'Apollo Tyres' },
  { symbol: 'ASHOKLEY', name: 'Ashok Leyland' },
  { symbol: 'ASIANPAINT', name: 'Asian Paints' },
  { symbol: 'ASTRAL', name: 'Astral Ltd' },
  { symbol: 'ATUL', name: 'Atul Ltd' },
  { symbol: 'AUROPHARMA', name: 'Aurobindo Pharma' },
  { symbol: 'AXISBANK', name: 'Axis Bank' },
  { symbol: 'BAJAJ-AUTO', name: 'Bajaj Auto' },
  { symbol: 'BAJAJFINSV', name: 'Bajaj Finserv' },
  { symbol: 'BAJAJHLDNG', name: 'Bajaj Holdings & Investment' },
  { symbol: 'BAJFINANCE', name: 'Bajaj Finance' },
  { symbol: 'BALKRISIND', name: 'Balkrishna Industries' },
  { symbol: 'BANDHANBNK', name: 'Bandhan Bank' },
  { symbol: 'BANKBARODA', name: 'Bank of Baroda' },
  { symbol: 'BATAINDIA', name: 'Bata India' },
  { symbol: 'BEL', name: 'Bharat Electronics' },
  { symbol: 'BERGEPAINT', name: 'Berger Paints India' },
  { symbol: 'BHARTIARTL', name: 'Bharti Airtel' },
  { symbol: 'BHEL', name: 'Bharat Heavy Electricals' },
  { symbol: 'BIOCON', name: 'Biocon' },
  { symbol: 'BOSCHLTD', name: 'Bosch Ltd' },
  { symbol: 'BPCL', name: 'Bharat Petroleum Corp' },
  { symbol: 'BRITANNIA', name: 'Britannia Industries' },
  { symbol: 'BSOFT', name: 'BIRLASOFT' },
  { symbol: 'CAMS', name: 'Computer Age Management Services' },
  { symbol: 'CANBK', name: 'Canara Bank' },
  { symbol: 'CANFINHOME', name: 'Can Fin Homes' },
  { symbol: 'CGPOWER', name: 'CG Power & Industrial Solutions' },
  { symbol: 'CHAMBLFERT', name: 'Chambal Fertilisers' },
  { symbol: 'CHOLAFIN', name: 'Cholamandalam Investment & Finance' },
  { symbol: 'CIPLA', name: 'Cipla' },
  { symbol: 'COALINDIA', name: 'Coal India' },
  { symbol: 'COFORGE', name: 'Coforge' },
  { symbol: 'COLPAL', name: 'Colgate-Palmolive India' },
  { symbol: 'CONCOR', name: 'Container Corporation of India' },
  { symbol: 'COROMANDEL', name: 'Coromandel International' },
  { symbol: 'CROMPTON', name: 'Crompton Greaves Consumer Electricals' },
  { symbol: 'CUB', name: 'City Union Bank' },
  { symbol: 'CUMMINSIND', name: 'Cummins India' },
  { symbol: 'DABUR', name: 'Dabur India' },
  { symbol: 'DALBHARAT', name: 'Dalmia Bharat' },
  { symbol: 'DEEPAKNTR', name: 'Deepak Nitrite' },
  { symbol: 'DELHIVERY', name: 'Delhivery' },
  { symbol: 'DELTACORP', name: 'Delta Corp' },
  { symbol: 'DIVISLAB', name: "Divi's Laboratories" },
  { symbol: 'DIXON', name: 'Dixon Technologies India' },
  { symbol: 'DLF', name: 'DLF' },
  { symbol: 'DMART', name: 'Avenue Supermarts (DMart)' },
  { symbol: 'DRREDDY', name: "Dr. Reddy's Laboratories" },
  { symbol: 'EICHERMOT', name: 'Eicher Motors' },
  { symbol: 'EMAMILTD', name: 'Emami' },
  { symbol: 'ESCORTS', name: 'Escorts Kubota' },
  { symbol: 'EXIDEIND', name: 'Exide Industries' },
  { symbol: 'FEDERALBNK', name: 'Federal Bank' },
  { symbol: 'FINNIFTY', name: 'Nifty Financial Services Index' },
  { symbol: 'FORTIS', name: 'Fortis Healthcare' },
  { symbol: 'GAIL', name: 'GAIL (India)' },
  { symbol: 'GLENMARK', name: 'Glenmark Pharmaceuticals' },
  { symbol: 'GMRINFRA', name: 'GMR Airports Infrastructure' },
  { symbol: 'GODREJCP', name: 'Godrej Consumer Products' },
  { symbol: 'GODREJPROP', name: 'Godrej Properties' },
  { symbol: 'GRANULES', name: 'Granules India' },
  { symbol: 'GRASIM', name: 'Grasim Industries' },
  { symbol: 'GSPL', name: 'Gujarat State Petronet' },
  { symbol: 'GUJGASLTD', name: 'Gujarat Gas' },
  { symbol: 'HAL', name: 'Hindustan Aeronautics' },
  { symbol: 'HAVELLS', name: 'Havells India' },
  { symbol: 'HCLTECH', name: 'HCL Technologies' },
  { symbol: 'HDFCBANK', name: 'HDFC Bank' },
  { symbol: 'HDFCLIFE', name: 'HDFC Life Insurance' },
  { symbol: 'HEROMOTOCO', name: 'Hero MotoCorp' },
  { symbol: 'HINDALCO', name: 'Hindalco Industries' },
  { symbol: 'HINDCOPPER', name: 'Hindustan Copper' },
  { symbol: 'HINDPETRO', name: 'Hindustan Petroleum Corp' },
  { symbol: 'HINDUNILVR', name: 'Hindustan Unilever' },
  { symbol: 'HONASA', name: 'Honasa Consumer (Mamaearth)' },
  { symbol: 'IBREALEST', name: 'Indiabulls Real Estate' },
  { symbol: 'ICICIBANK', name: 'ICICI Bank' },
  { symbol: 'ICICIGI', name: 'ICICI Lombard General Insurance' },
  { symbol: 'ICICIPRULI', name: 'ICICI Prudential Life Insurance' },
  { symbol: 'IDEA', name: 'Vodafone Idea' },
  { symbol: 'IDFCFIRSTB', name: 'IDFC First Bank' },
  { symbol: 'IEX', name: 'Indian Energy Exchange' },
  { symbol: 'IGL', name: 'Indraprastha Gas' },
  { symbol: 'INDHOTEL', name: 'Indian Hotels Company' },
  { symbol: 'INDIAMART', name: 'IndiaMART InterMESH' },
  { symbol: 'INDIACEM', name: 'India Cements' },
  { symbol: 'INDIGO', name: 'InterGlobe Aviation (IndiGo)' },
  { symbol: 'INDUSINDBK', name: 'IndusInd Bank' },
  { symbol: 'INDUSTOWER', name: 'Indus Towers' },
  { symbol: 'INFY', name: 'Infosys' },
  { symbol: 'IOC', name: 'Indian Oil Corporation' },
  { symbol: 'IRCTC', name: 'Indian Railway Catering & Tourism Corp' },
  { symbol: 'IRFC', name: 'Indian Railway Finance Corp' },
  { symbol: 'ITC', name: 'ITC' },
  { symbol: 'JINDALSTEL', name: 'Jindal Steel & Power' },
  { symbol: 'JIOFIN', name: 'Jio Financial Services' },
  { symbol: 'JKCEMENT', name: 'JK Cement' },
  { symbol: 'JSL', name: 'Jindal Stainless' },
  { symbol: 'JSWENERGY', name: 'JSW Energy' },
  { symbol: 'JSWSTEEL', name: 'JSW Steel' },
  { symbol: 'JUBLFOOD', name: 'Jubilant FoodWorks' },
  { symbol: 'KALYANKJIL', name: 'Kalyan Jewellers India' },
  { symbol: 'KOTAKBANK', name: 'Kotak Mahindra Bank' },
  { symbol: 'L&TFH', name: 'L&T Finance' },
  { symbol: 'LALPATHLAB', name: 'Dr. Lal PathLabs' },
  { symbol: 'LAURUSLABS', name: 'Laurus Labs' },
  { symbol: 'LICHSGFIN', name: 'LIC Housing Finance' },
  { symbol: 'LICI', name: 'Life Insurance Corporation of India' },
  { symbol: 'LODHA', name: 'Macrotech Developers (Lodha)' },
  { symbol: 'LT', name: 'Larsen & Toubro' },
  { symbol: 'LTIM', name: 'LTIMindtree' },
  { symbol: 'LTTS', name: 'L&T Technology Services' },
  { symbol: 'LUPIN', name: 'Lupin' },
  { symbol: 'M&M', name: 'Mahindra & Mahindra' },
  { symbol: 'M&MFIN', name: 'Mahindra & Mahindra Financial Services' },
  { symbol: 'MANAPPURAM', name: 'Manappuram Finance' },
  { symbol: 'MARICO', name: 'Marico' },
  { symbol: 'MARUTI', name: 'Maruti Suzuki India' },
  { symbol: 'MAXHEALTH', name: 'Max Healthcare Institute' },
  { symbol: 'MCX', name: 'Multi Commodity Exchange of India' },
  { symbol: 'METROPOLIS', name: 'Metropolis Healthcare' },
  { symbol: 'MFSL', name: 'Max Financial Services' },
  { symbol: 'MPHASIS', name: 'Mphasis' },
  { symbol: 'MRF', name: 'MRF' },
  { symbol: 'MUTHOOTFIN', name: 'Muthoot Finance' },
  { symbol: 'NAUKRI', name: 'Info Edge India (Naukri)' },
  { symbol: 'NAVINFLUOR', name: 'Navin Fluorine International' },
  { symbol: 'NESTLEIND', name: 'Nestle India' },
  { symbol: 'NHPC', name: 'NHPC' },
  { symbol: 'NMDC', name: 'NMDC' },
  { symbol: 'NTPC', name: 'NTPC' },
  { symbol: 'NYKAA', name: 'FSN E-Commerce Ventures (Nykaa)' },
  { symbol: 'OBEROIRLTY', name: 'Oberoi Realty' },
  { symbol: 'OFSS', name: 'Oracle Financial Services Software' },
  { symbol: 'ONGC', name: 'Oil & Natural Gas Corp' },
  { symbol: 'PAGEIND', name: 'Page Industries' },
  { symbol: 'PAYTM', name: 'One97 Communications (Paytm)' },
  { symbol: 'PERSISTENT', name: 'Persistent Systems' },
  { symbol: 'PETRONET', name: 'Petronet LNG' },
  { symbol: 'PFC', name: 'Power Finance Corporation' },
  { symbol: 'PHOENIXLTD', name: 'Phoenix Mills' },
  { symbol: 'PIDILITIND', name: 'Pidilite Industries' },
  { symbol: 'PIIND', name: 'PI Industries' },
  { symbol: 'PNB', name: 'Punjab National Bank' },
  { symbol: 'POLYCAB', name: 'Polycab India' },
  { symbol: 'POWERGRID', name: 'Power Grid Corporation of India' },
  { symbol: 'PRESTIGE', name: 'Prestige Estates Projects' },
  { symbol: 'PVRINOX', name: 'PVR INOX' },
  { symbol: 'RAMCOCEM', name: 'Ramco Cements' },
  { symbol: 'RBLBANK', name: 'RBL Bank' },
  { symbol: 'RECLTD', name: 'REC' },
  { symbol: 'RELIANCE', name: 'Reliance Industries' },
  { symbol: 'SAIL', name: 'Steel Authority of India' },
  { symbol: 'SBICARD', name: 'SBI Cards & Payment Services' },
  { symbol: 'SBILIFE', name: 'SBI Life Insurance' },
  { symbol: 'SBIN', name: 'State Bank of India' },
  { symbol: 'SHREECEM', name: 'Shree Cement' },
  { symbol: 'SHRIRAMFIN', name: 'Shriram Finance' },
  { symbol: 'SIEMENS', name: 'Siemens' },
  { symbol: 'SOBHA', name: 'Sobha' },
  { symbol: 'SRF', name: 'SRF' },
  { symbol: 'SUNPHARMA', name: 'Sun Pharmaceutical Industries' },
  { symbol: 'SUNTV', name: 'Sun TV Network' },
  { symbol: 'SUPREMEIND', name: 'Supreme Industries' },
  { symbol: 'SYNGENE', name: 'Syngene International' },
  { symbol: 'TATACOMM', name: 'Tata Communications' },
  { symbol: 'TATACONSUM', name: 'Tata Consumer Products' },
  { symbol: 'TATAELXSI', name: 'Tata Elxsi' },
  { symbol: 'TATAMOTORS', name: 'Tata Motors' },
  { symbol: 'TATAPOWER', name: 'Tata Power' },
  { symbol: 'TATASTEEL', name: 'Tata Steel' },
  { symbol: 'TCS', name: 'Tata Consultancy Services' },
  { symbol: 'TECHM', name: 'Tech Mahindra' },
  { symbol: 'TITAN', name: 'Titan Company' },
  { symbol: 'TORNTPHARM', name: 'Torrent Pharmaceuticals' },
  { symbol: 'TORNTPOWER', name: 'Torrent Power' },
  { symbol: 'TRENT', name: 'Trent' },
  { symbol: 'TRIDENT', name: 'Trident' },
  { symbol: 'UBL', name: 'United Breweries' },
  { symbol: 'UJJIVANSFB', name: 'Ujjivan Small Finance Bank' },
  { symbol: 'ULTRACEMCO', name: 'UltraTech Cement' },
  { symbol: 'UPL', name: 'UPL' },
  { symbol: 'VBL', name: 'Varun Beverages' },
  { symbol: 'VEDL', name: 'Vedanta' },
  { symbol: 'VOLTAS', name: 'Voltas' },
  { symbol: 'WHIRLPOOL', name: 'Whirlpool of India' },
  { symbol: 'WIPRO', name: 'Wipro' },
  { symbol: 'YESBANK', name: 'Yes Bank' },
  { symbol: 'ZEEL', name: 'Zee Entertainment Enterprises' },
  { symbol: 'ZOMATO', name: 'Zomato' },
  { symbol: 'ZYDUSLIFE', name: 'Zydus Lifesciences' },
  // Additional NSE stocks (Nifty 500 + F&O list)
  { symbol: 'AAVAS', name: 'AAVAS Financiers' },
  { symbol: 'AETHER', name: 'Aether Industries' },
  { symbol: 'AFFLE', name: 'Affle India' },
  { symbol: 'AIAENG', name: 'AIA Engineering' },
  { symbol: 'AJANTPHARM', name: 'Ajanta Pharma' },
  { symbol: 'AKZOINDIA', name: 'Akzo Nobel India' },
  { symbol: 'AMARAJABAT', name: 'Amara Raja Energy & Mobility' },
  { symbol: 'AMBER', name: 'Amber Enterprises India' },
  { symbol: 'ANANTRAJ', name: 'Anant Raj' },
  { symbol: 'APLAPOLLO', name: 'APL Apollo Tubes' },
  { symbol: 'APARINDS', name: 'Apar Industries' },
  { symbol: 'APTUS', name: 'Aptus Value Housing Finance' },
  { symbol: 'ATGL', name: 'Adani Total Gas' },
  { symbol: 'AUBANK', name: 'AU Small Finance Bank' },
  { symbol: 'AVANTIFEED', name: 'Avanti Feeds' },
  { symbol: 'BALAMINES', name: 'Balaji Amines' },
  { symbol: 'BALRAMCHIN', name: 'Balrampur Chini Mills' },
  { symbol: 'BANKINDIA', name: 'Bank of India' },
  { symbol: 'BASF', name: 'BASF India' },
  { symbol: 'BAYERCROP', name: 'Bayer CropScience' },
  { symbol: 'BDL', name: 'Bharat Dynamics' },
  { symbol: 'BEML', name: 'BEML' },
  { symbol: 'BIRLACORPN', name: 'Birla Corporation' },
  { symbol: 'BLUEDART', name: 'Blue Dart Express' },
  { symbol: 'BLUESTARCO', name: 'Blue Star' },
  { symbol: 'BRIGADE', name: 'Brigade Enterprises' },
  { symbol: 'CAPLIPOINT', name: 'Caplin Point Laboratories' },
  { symbol: 'CARBORUNIV', name: 'Carborundum Universal' },
  { symbol: 'CDSL', name: 'Central Depository Services India' },
  { symbol: 'CEATLTD', name: 'CEAT' },
  { symbol: 'CENTRALBK', name: 'Central Bank of India' },
  { symbol: 'CESC', name: 'CESC' },
  { symbol: 'CHALET', name: 'Chalet Hotels' },
  { symbol: 'CLEAN', name: 'Clean Science & Technology' },
  { symbol: 'CMSINFO', name: 'CMS Info Systems' },
  { symbol: 'CRAFTSMAN', name: 'Craftsman Automation' },
  { symbol: 'CRISIL', name: 'CRISIL' },
  { symbol: 'CYIENT', name: 'Cyient' },
  { symbol: 'DATAPATTNS', name: 'Data Patterns India' },
  { symbol: 'DCBBANK', name: 'DCB Bank' },
  { symbol: 'DCMSHRIRAM', name: 'DCM Shriram' },
  { symbol: 'DEEPAKFERT', name: 'Deepak Fertilisers & Petrochemicals' },
  { symbol: 'DHANUKA', name: 'Dhanuka Agritech' },
  { symbol: 'DODLA', name: 'Dodla Dairy' },
  { symbol: 'EASEMYTRIP', name: 'Easy Trip Planners' },
  { symbol: 'EIDPARRY', name: 'EID Parry India' },
  { symbol: 'ELGIEQUIP', name: 'Elgi Equipments' },
  { symbol: 'ENDURANCE', name: 'Endurance Technologies' },
  { symbol: 'EPIGRAL', name: 'Epigral' },
  { symbol: 'EQUITASBNK', name: 'Equitas Small Finance Bank' },
  { symbol: 'ESAFSFB', name: 'ESAF Small Finance Bank' },
  { symbol: 'ETHOSLTD', name: 'Ethos' },
  { symbol: 'FACT', name: 'Fertilisers & Chemicals Travancore' },
  { symbol: 'FINCABLES', name: 'Finolex Cables' },
  { symbol: 'FINEORG', name: 'Fine Organic Industries' },
  { symbol: 'FINPIPE', name: 'Finolex Industries' },
  { symbol: 'FLUOROCHEM', name: 'Gujarat Fluorochemicals' },
  { symbol: 'FORCEMOT', name: 'Force Motors' },
  { symbol: 'GAEL', name: 'Gujarat Ambuja Exports' },
  { symbol: 'GABRIEL', name: 'Gabriel India' },
  { symbol: 'GALAXYSURF', name: 'Galaxy Surfactants' },
  { symbol: 'GARFIBRES', name: 'Garware Technical Fibres' },
  { symbol: 'GESHIP', name: 'Great Eastern Shipping' },
  { symbol: 'GICRE', name: 'General Insurance Corporation of India' },
  { symbol: 'GILLETTE', name: 'Gillette India' },
  { symbol: 'GLAND', name: 'Gland Pharma' },
  { symbol: 'GLOBUSSPR', name: 'Globus Spirits' },
  { symbol: 'GNFC', name: 'Gujarat Narmada Valley Fertilizers' },
  { symbol: 'GPIL', name: 'Godawari Power & Ispat' },
  { symbol: 'GRAPHITE', name: 'Graphite India' },
  { symbol: 'GREENPANEL', name: 'Greenpanel Industries' },
  { symbol: 'GRINDWELL', name: 'Grindwell Norton' },
  { symbol: 'GUJALKALI', name: 'Gujarat Alkalies & Chemicals' },
  { symbol: 'HAPPSTMNDS', name: 'Happiest Minds Technologies' },
  { symbol: 'HEG', name: 'HEG' },
  { symbol: 'HEIDELBERG', name: 'HeidelbergCement India' },
  { symbol: 'HGINFRA', name: 'HG Infra Engineering' },
  { symbol: 'HIKAL', name: 'Hikal' },
  { symbol: 'HONAUT', name: 'Honeywell Automation India' },
  { symbol: 'HSCL', name: 'Himadri Speciality Chemical' },
  { symbol: 'HUDCO', name: 'Housing & Urban Development Corp' },
  { symbol: 'IBULHSGFIN', name: 'Indiabulls Housing Finance' },
  { symbol: 'IDBI', name: 'IDBI Bank' },
  { symbol: 'IFCI', name: 'IFCI' },
  { symbol: 'INDIANB', name: 'Indian Bank' },
  { symbol: 'INDIGOPNTS', name: 'Indigo Paints' },
  { symbol: 'INTELLECT', name: 'Intellect Design Arena' },
  { symbol: 'IOB', name: 'Indian Overseas Bank' },
  { symbol: 'IOLCP', name: 'IOL Chemicals & Pharmaceuticals' },
  { symbol: 'IPCA', name: 'IPCA Laboratories' },
  { symbol: 'IRCON', name: 'Ircon International' },
  { symbol: 'IREDA', name: 'Indian Renewable Energy Dev Agency' },
  { symbol: 'ITDCEM', name: 'ITD Cementation India' },
  { symbol: 'JAMNAAUTO', name: 'Jamna Auto Industries' },
  { symbol: 'JBCHEPHARM', name: 'J.B. Chemicals & Pharmaceuticals' },
  { symbol: 'JKPAPER', name: 'JK Paper' },
  { symbol: 'JKTYRE', name: 'JK Tyre & Industries' },
  { symbol: 'JMFINANCL', name: 'JM Financial' },
  { symbol: 'JPPOWER', name: 'Jaiprakash Power Ventures' },
  { symbol: 'KALPATPOWR', name: 'Kalpataru Projects International' },
  { symbol: 'KANSAINER', name: 'Kansai Nerolac Paints' },
  { symbol: 'KAYNES', name: 'Kaynes Technology India' },
  { symbol: 'KECIL', name: 'KEC International' },
  { symbol: 'KEI', name: 'KEI Industries' },
  { symbol: 'KIOCL', name: 'KIOCL' },
  { symbol: 'KNRCON', name: 'KNR Constructions' },
  { symbol: 'KOLTEPATIL', name: 'Kolte-Patil Developers' },
  { symbol: 'KPITTECH', name: 'KPIT Technologies' },
  { symbol: 'KRBL', name: 'KRBL' },
  { symbol: 'LATENTVIEW', name: 'LatentView Analytics' },
  { symbol: 'LAXMIMACH', name: 'Laxmi Machine Works' },
  { symbol: 'LEMONTREE', name: 'Lemon Tree Hotels' },
  { symbol: 'LGBBROSLTD', name: 'LG Balakrishnan & Bros' },
  { symbol: 'LINDEINDIA', name: 'Linde India' },
  { symbol: 'LLOYDSME', name: 'Lloyds Metals & Energy' },
  { symbol: 'MAHLIFE', name: 'Mahindra Lifespace Developers' },
  { symbol: 'MAHSEAMLES', name: 'Maharashtra Seamless' },
  { symbol: 'MANKIND', name: 'Mankind Pharma' },
  { symbol: 'MAPMYINDIA', name: 'CE Info Systems (MapmyIndia)' },
  { symbol: 'MAZAGON', name: 'Mazagon Dock Shipbuilders' },
  { symbol: 'MEDANTA', name: 'Global Health (Medanta)' },
  { symbol: 'MHRIL', name: 'Mahindra Holidays & Resorts India' },
  { symbol: 'MIDHANI', name: 'Mishra Dhatu Nigam' },
  { symbol: 'MINDA', name: 'Minda Corporation' },
  { symbol: 'MMTC', name: 'MMTC' },
  { symbol: 'MOIL', name: 'MOIL' },
  { symbol: 'MOTHERSON', name: 'Samvardhana Motherson International' },
  { symbol: 'MSTCLTD', name: 'MSTC' },
  { symbol: 'NALCO', name: 'National Aluminium Company' },
  { symbol: 'NATCOPHARM', name: 'Natco Pharma' },
  { symbol: 'NBCC', name: 'NBCC India' },
  { symbol: 'NCC', name: 'NCC' },
  { symbol: 'NESCO', name: 'Nesco' },
  { symbol: 'NETWORK18', name: 'Network18 Media & Investments' },
  { symbol: 'NEULANDLAB', name: 'Neuland Laboratories' },
  { symbol: 'NILKAMAL', name: 'Nilkamal' },
  { symbol: 'NLCINDIA', name: 'NLC India' },
  { symbol: 'NOCIL', name: 'NOCIL' },
  { symbol: 'NUVAMA', name: 'Nuvama Wealth Management' },
  { symbol: 'NUVOCO', name: 'Nuvoco Vistas Corporation' },
  { symbol: 'OIL', name: 'Oil India' },
  { symbol: 'OLECTRA', name: 'Olectra Greentech' },
  { symbol: 'ORIENTCEM', name: 'Orient Cement' },
  { symbol: 'ORIENTELEC', name: 'Orient Electric' },
  { symbol: 'PARADEEP', name: 'Paradeep Phosphates' },
  { symbol: 'PARAS', name: 'Paras Defence & Space Technologies' },
  { symbol: 'PATANJALI', name: 'Patanjali Foods' },
  { symbol: 'PCBL', name: 'PCBL' },
  { symbol: 'PGHL', name: 'Procter & Gamble Health' },
  { symbol: 'PGHH', name: 'Procter & Gamble Hygiene & Health Care' },
  { symbol: 'PHILIPCARB', name: 'Phillips Carbon Black' },
  { symbol: 'PNBHOUSING', name: 'PNB Housing Finance' },
  { symbol: 'PNC', name: 'PNC Infratech' },
  { symbol: 'POLYMED', name: 'Poly Medicure' },
  { symbol: 'POONAWALLA', name: 'Poonawalla Fincorp' },
  { symbol: 'POWERMECH', name: 'Power Mech Projects' },
  { symbol: 'RADICO', name: 'Radico Khaitan' },
  { symbol: 'RAILTEL', name: 'RailTel Corporation of India' },
  { symbol: 'RAINBOW', name: 'Rainbow Childrens Medicare' },
  { symbol: 'RAJESHEXPO', name: 'Rajesh Exports' },
  { symbol: 'RATNAMANI', name: 'Ratnamani Metals & Tubes' },
  { symbol: 'RAYMOND', name: 'Raymond' },
  { symbol: 'RENUKA', name: 'Shree Renuka Sugars' },
  { symbol: 'RITES', name: 'RITES' },
  { symbol: 'ROSSARI', name: 'Rossari Biotech' },
  { symbol: 'ROUTE', name: 'Route Mobile' },
  { symbol: 'RPOWER', name: 'Reliance Power' },
  { symbol: 'RVNL', name: 'Rail Vikas Nigam' },
  { symbol: 'SAFARI', name: 'Safari Industries India' },
  { symbol: 'SAPPHIRE', name: 'Sapphire Foods India' },
  { symbol: 'SCHAEFFLER', name: 'Schaeffler India' },
  { symbol: 'SEQUENT', name: 'SeQuent Scientific' },
  { symbol: 'SHYAMMETL', name: 'Shyam Metalics & Energy' },
  { symbol: 'SIGNATURE', name: 'Signature Global India' },
  { symbol: 'SJVN', name: 'SJVN' },
  { symbol: 'SKFINDIA', name: 'SKF India' },
  { symbol: 'SONACOMS', name: 'Sona BLW Precision Forgings' },
  { symbol: 'SPANDANA', name: 'Spandana Sphoorty Financial' },
  { symbol: 'SPARC', name: 'Sun Pharma Advanced Research' },
  { symbol: 'STARCEMENT', name: 'Star Cement' },
  { symbol: 'STLTECH', name: 'Sterlite Technologies' },
  { symbol: 'SUBROS', name: 'Subros' },
  { symbol: 'SUMICHEM', name: 'Sumitomo Chemical India' },
  { symbol: 'SUNDARMFIN', name: 'Sundaram Finance' },
  { symbol: 'SUNTECK', name: 'Sunteck Realty' },
  { symbol: 'SUPRAJIT', name: 'Suprajit Engineering' },
  { symbol: 'SUZLON', name: 'Suzlon Energy' },
  { symbol: 'SYRMA', name: 'Syrma SGS Technology' },
  { symbol: 'TANLA', name: 'Tanla Platforms' },
  { symbol: 'TATACHEM', name: 'Tata Chemicals' },
  { symbol: 'TATAINVEST', name: 'Tata Investment Corporation' },
  { symbol: 'TATATECH', name: 'Tata Technologies' },
  { symbol: 'TEAMLEASE', name: 'TeamLease Services' },
  { symbol: 'TEJASNET', name: 'Tejas Networks' },
  { symbol: 'THERMAX', name: 'Thermax' },
  { symbol: 'TIMKEN', name: 'Timken India' },
  { symbol: 'TIMETECHNO', name: 'Time Technoplast' },
  { symbol: 'TITAGARH', name: 'Titagarh Rail Systems' },
  { symbol: 'TRIVENI', name: 'Triveni Engineering & Industries' },
  { symbol: 'TVSMOTOR', name: 'TVS Motor Company' },
  { symbol: 'UCOBANK', name: 'UCO Bank' },
  { symbol: 'UNIONBANK', name: 'Union Bank of India' },
  { symbol: 'UNITDSPR', name: 'United Spirits' },
  { symbol: 'UPDATER', name: 'Updater Services' },
  { symbol: 'UTKARSHBNK', name: 'Utkarsh Small Finance Bank' },
  { symbol: 'VAIBHAVGBL', name: 'Vaibhav Global' },
  { symbol: 'VARDHMAN', name: 'Vardhman Textiles' },
  { symbol: 'VESUVIUS', name: 'Vesuvius India' },
  { symbol: 'VGUARD', name: 'V-Guard Industries' },
  { symbol: 'VINATIORGA', name: 'Vinati Organics' },
  { symbol: 'VIPIND', name: 'VIP Industries' },
  { symbol: 'VMART', name: 'V-Mart Retail' },
  { symbol: 'VSTIND', name: 'VST Industries' },
  { symbol: 'WELCORP', name: 'Welspun Corp' },
  { symbol: 'WELSPUNLIV', name: 'Welspun Living' },
  { symbol: 'WESTLIFE', name: 'Westlife Foodworld' },
  { symbol: 'WOCKPHARMA', name: 'Wockhardt' },
  { symbol: 'WONDERLA', name: 'Wonderla Holidays' },
  { symbol: 'WSTCSTPAPR', name: 'West Coast Paper Mills' },
  { symbol: 'ZENSARTECH', name: 'Zensar Technologies' },
];

// BSE-specific or BSE-primary stocks
export const BSE_STOCKS: StockEntry[] = [
  { symbol: 'BANKEX', name: 'BSE Bankex Index' },
  { symbol: 'SENSEX', name: 'BSE Sensex Index' },
  // BSE uses same symbols as NSE for most stocks
  ...NSE_STOCKS,
];

export function searchStocks(query: string, exchange: 'NSE' | 'BSE'): StockEntry[] {
  if (!query || query.length < 1) return [];
  const q = query.toUpperCase();
  const list = exchange === 'BSE' ? BSE_STOCKS : NSE_STOCKS;
  return list
    .filter(s =>
      s.symbol.startsWith(q) ||
      s.name.toUpperCase().includes(q) ||
      s.symbol.includes(q)
    )
    .slice(0, 12);
}
