export interface StockEntry {
  symbol: string;
  name: string;
}

// NSE F&O + major listed stocks
export const NSE_STOCKS: StockEntry[] = [
  { symbol: 'AARTIIND', name: 'Aarti Industries' },
  { symbol: 'ABB', name: 'ABB India' },
  { symbol: 'ABCAPITAL', name: 'Aditya Birla Capital' },
  { symbol: 'ABFRL', name: 'Aditya Birla Fashion & Retail' },
  { symbol: 'ACC', name: 'ACC Ltd' },
  { symbol: 'ADANIENSOL', name: 'Adani Energy Solutions' },
  { symbol: 'ADANIENT', name: 'Adani Enterprises' },
  { symbol: 'ADANIGREEN', name: 'Adani Green Energy' },
  { symbol: 'ADANIPORTS', name: 'Adani Ports & SEZ' },
  { symbol: 'ADANIPOWER', name: 'Adani Power' },
  { symbol: 'ALKEM', name: 'Alkem Laboratories' },
  { symbol: 'AMBUJACEM', name: 'Ambuja Cements' },
  { symbol: 'ANGELONE', name: 'Angel One' },
  { symbol: 'APOLLOHOSP', name: 'Apollo Hospitals Enterprise' },
  { symbol: 'APOLLOTYRE', name: 'Apollo Tyres' },
  { symbol: 'ASHOKLEY', name: 'Ashok Leyland' },
  { symbol: 'ASIANPAINT', name: 'Asian Paints' },
  { symbol: 'ASTRAL', name: 'Astral Ltd' },
  { symbol: 'ATUL', name: 'Atul Ltd' },
  { symbol: 'AUROPHARMA', name: 'Aurobindo Pharma' },
  { symbol: 'AXISBANK', name: 'Axis Bank' },
  { symbol: 'BAJAJ-AUTO', name: 'Bajaj Auto' },
  { symbol: 'BAJAJFINSV', name: 'Bajaj Finserv' },
  { symbol: 'BAJAJHLDNG', name: 'Bajaj Holdings & Investment' },
  { symbol: 'BAJFINANCE', name: 'Bajaj Finance' },
  { symbol: 'BALKRISIND', name: 'Balkrishna Industries' },
  { symbol: 'BANDHANBNK', name: 'Bandhan Bank' },
  { symbol: 'BANKBARODA', name: 'Bank of Baroda' },
  { symbol: 'BATAINDIA', name: 'Bata India' },
  { symbol: 'BEL', name: 'Bharat Electronics' },
  { symbol: 'BERGEPAINT', name: 'Berger Paints India' },
  { symbol: 'BHARTIARTL', name: 'Bharti Airtel' },
  { symbol: 'BHEL', name: 'Bharat Heavy Electricals' },
  { symbol: 'BIOCON', name: 'Biocon' },
  { symbol: 'BOSCHLTD', name: 'Bosch Ltd' },
  { symbol: 'BPCL', name: 'Bharat Petroleum Corp' },
  { symbol: 'BRITANNIA', name: 'Britannia Industries' },
  { symbol: 'BSOFT', name: 'BIRLASOFT' },
  { symbol: 'CAMS', name: 'Computer Age Management Services' },
  { symbol: 'CANBK', name: 'Canara Bank' },
  { symbol: 'CANFINHOME', name: 'Can Fin Homes' },
  { symbol: 'CGPOWER', name: 'CG Power & Industrial Solutions' },
  { symbol: 'CHAMBLFERT', name: 'Chambal Fertilisers' },
  { symbol: 'CHOLAFIN', name: 'Cholamandalam Investment & Finance' },
  { symbol: 'CIPLA', name: 'Cipla' },
  { symbol: 'COALINDIA', name: 'Coal India' },
  { symbol: 'COFORGE', name: 'Coforge' },
  { symbol: 'COLPAL', name: 'Colgate-Palmolive India' },
  { symbol: 'CONCOR', name: 'Container Corporation of India' },
  { symbol: 'COROMANDEL', name: 'Coromandel International' },
  { symbol: 'CROMPTON', name: 'Crompton Greaves Consumer Electricals' },
  { symbol: 'CUB', name: 'City Union Bank' },
  { symbol: 'CUMMINSIND', name: 'Cummins India' },
  { symbol: 'DABUR', name: 'Dabur India' },
  { symbol: 'DALBHARAT', name: 'Dalmia Bharat' },
  { symbol: 'DEEPAKNTR', name: 'Deepak Nitrite' },
  { symbol: 'DELHIVERY', name: 'Delhivery' },
  { symbol: 'DELTACORP', name: 'Delta Corp' },
  { symbol: 'DIVISLAB', name: "Divi's Laboratories" },
  { symbol: 'DIXON', name: 'Dixon Technologies India' },
  { symbol: 'DLF', name: 'DLF' },
  { symbol: 'DMART', name: 'Avenue Supermarts (DMart)' },
  { symbol: 'DRREDDY', name: "Dr. Reddy's Laboratories" },
  { symbol: 'EICHERMOT', name: 'Eicher Motors' },
  { symbol: 'EMAMILTD', name: 'Emami' },
  { symbol: 'ESCORTS', name: 'Escorts Kubota' },
  { symbol: 'EXIDEIND', name: 'Exide Industries' },
  { symbol: 'FEDERALBNK', name: 'Federal Bank' },
  { symbol: 'FINNIFTY', name: 'Nifty Financial Services Index' },
  { symbol: 'FORTIS', name: 'Fortis Healthcare' },
  { symbol: 'GAIL', name: 'GAIL (India)' },
  { symbol: 'GLENMARK', name: 'Glenmark Pharmaceuticals' },
  { symbol: 'GMRINFRA', name: 'GMR Airports Infrastructure' },
  { symbol: 'GODREJCP', name: 'Godrej Consumer Products' },
  { symbol: 'GODREJPROP', name: 'Godrej Properties' },
  { symbol: 'GRANULES', name: 'Granules India' },
  { symbol: 'GRASIM', name: 'Grasim Industries' },
  { symbol: 'GSPL', name: 'Gujarat State Petronet' },
  { symbol: 'GUJGASLTD', name: 'Gujarat Gas' },
  { symbol: 'HAL', name: 'Hindustan Aeronautics' },
  { symbol: 'HAVELLS', name: 'Havells India' },
  { symbol: 'HCLTECH', name: 'HCL Technologies' },
  { symbol: 'HDFCBANK', name: 'HDFC Bank' },
  { symbol: 'HDFCLIFE', name: 'HDFC Life Insurance' },
  { symbol: 'HEROMOTOCO', name: 'Hero MotoCorp' },
  { symbol: 'HINDALCO', name: 'Hindalco Industries' },
  { symbol: 'HINDCOPPER', name: 'Hindustan Copper' },
  { symbol: 'HINDPETRO', name: 'Hindustan Petroleum Corp' },
  { symbol: 'HINDUNILVR', name: 'Hindustan Unilever' },
  { symbol: 'HONASA', name: 'Honasa Consumer (Mamaearth)' },
  { symbol: 'IBREALEST', name: 'Indiabulls Real Estate' },
  { symbol: 'ICICIBANK', name: 'ICICI Bank' },
  { symbol: 'ICICIGI', name: 'ICICI Lombard General Insurance' },
  { symbol: 'ICICIPRULI', name: 'ICICI Prudential Life Insurance' },
  { symbol: 'IDEA', name: 'Vodafone Idea' },
  { symbol: 'IDFCFIRSTB', name: 'IDFC First Bank' },
  { symbol: 'IEX', name: 'Indian Energy Exchange' },
  { symbol: 'IGL', name: 'Indraprastha Gas' },
  { symbol: 'INDHOTEL', name: 'Indian Hotels Company' },
  { symbol: 'INDIAMART', name: 'IndiaMART InterMESH' },
  { symbol: 'INDIACEM', name: 'India Cements' },
  { symbol: 'INDIGO', name: 'InterGlobe Aviation (IndiGo)' },
  { symbol: 'INDUSINDBK', name: 'IndusInd Bank' },
  { symbol: 'INDUSTOWER', name: 'Indus Towers' },
  { symbol: 'INFY', name: 'Infosys' },
  { symbol: 'IOC', name: 'Indian Oil Corporation' },
  { symbol: 'IRCTC', name: 'Indian Railway Catering & Tourism Corp' },
  { symbol: 'IRFC', name: 'Indian Railway Finance Corp' },
  { symbol: 'ITC', name: 'ITC' },
  { symbol: 'JINDALSTEL', name: 'Jindal Steel & Power' },
  { symbol: 'JIOFIN', name: 'Jio Financial Services' },
  { symbol: 'JKCEMENT', name: 'JK Cement' },
  { symbol: 'JSL', name: 'Jindal Stainless' },
  { symbol: 'JSWENERGY', name: 'JSW Energy' },
  { symbol: 'JSWSTEEL', name: 'JSW Steel' },
  { symbol: 'JUBLFOOD', name: 'Jubilant FoodWorks' },
  { symbol: 'KALYANKJIL', name: 'Kalyan Jewellers India' },
  { symbol: 'KOTAKBANK', name: 'Kotak Mahindra Bank' },
  { symbol: 'L&TFH', name: 'L&T Finance' },
  { symbol: 'LALPATHLAB', name: 'Dr. Lal PathLabs' },
  { symbol: 'LAURUSLABS', name: 'Laurus Labs' },
  { symbol: 'LICHSGFIN', name: 'LIC Housing Finance' },
  { symbol: 'LICI', name: 'Life Insurance Corporation of India' },
  { symbol: 'LODHA', name: 'Macrotech Developers (Lodha)' },
  { symbol: 'LT', name: 'Larsen & Toubro' },
  { symbol: 'LTIM', name: 'LTIMindtree' },
  { symbol: 'LTTS', name: 'L&T Technology Services' },
  { symbol: 'LUPIN', name: 'Lupin' },
  { symbol: 'M&M', name: 'Mahindra & Mahindra' },
  { symbol: 'M&MFIN', name: 'Mahindra & Mahindra Financial Services' },
  { symbol: 'MANAPPURAM', name: 'Manappuram Finance' },
  { symbol: 'MARICO', name: 'Marico' },
  { symbol: 'MARUTI', name: 'Maruti Suzuki India' },
  { symbol: 'MAXHEALTH', name: 'Max Healthcare Institute' },
  { symbol: 'MCX', name: 'Multi Commodity Exchange of India' },
  { symbol: 'METROPOLIS', name: 'Metropolis Healthcare' },
  { symbol: 'MFSL', name: 'Max Financial Services' },
  { symbol: 'MPHASIS', name: 'Mphasis' },
  { symbol: 'MRF', name: 'MRF' },
  { symbol: 'MUTHOOTFIN', name: 'Muthoot Finance' },
  { symbol: 'NAUKRI', name: 'Info Edge India (Naukri)' },
  { symbol: 'NAVINFLUOR', name: 'Navin Fluorine International' },
  { symbol: 'NESTLEIND', name: 'Nestle India' },
  { symbol: 'NHPC', name: 'NHPC' },
  { symbol: 'NMDC', name: 'NMDC' },
  { symbol: 'NTPC', name: 'NTPC' },
  { symbol: 'NYKAA', name: 'FSN E-Commerce Ventures (Nykaa)' },
  { symbol: 'OBEROIRLTY', name: 'Oberoi Realty' },
  { symbol: 'OFSS', name: 'Oracle Financial Services Software' },
  { symbol: 'ONGC', name: 'Oil & Natural Gas Corp' },
  { symbol: 'PAGEIND', name: 'Page Industries' },
  { symbol: 'PAYTM', name: 'One97 Communications (Paytm)' },
  { symbol: 'PERSISTENT', name: 'Persistent Systems' },
  { symbol: 'PETRONET', name: 'Petronet LNG' },
  { symbol: 'PFC', name: 'Power Finance Corporation' },
  { symbol: 'PHOENIXLTD', name: 'Phoenix Mills' },
  { symbol: 'PIDILITIND', name: 'Pidilite Industries' },
  { symbol: 'PIIND', name: 'PI Industries' },
  { symbol: 'PNB', name: 'Punjab National Bank' },
  { symbol: 'POLYCAB', name: 'Polycab India' },
  { symbol: 'POWERGRID', name: 'Power Grid Corporation of India' },
  { symbol: 'PRESTIGE', name: 'Prestige Estates Projects' },
  { symbol: 'PVRINOX', name: 'PVR INOX' },
  { symbol: 'RAMCOCEM', name: 'Ramco Cements' },
  { symbol: 'RBLBANK', name: 'RBL Bank' },
  { symbol: 'RECLTD', name: 'REC' },
  { symbol: 'RELIANCE', name: 'Reliance Industries' },
  { symbol: 'SAIL', name: 'Steel Authority of India' },
  { symbol: 'SBICARD', name: 'SBI Cards & Payment Services' },
  { symbol: 'SBILIFE', name: 'SBI Life Insurance' },
  { symbol: 'SBIN', name: 'State Bank of India' },
  { symbol: 'SHREECEM', name: 'Shree Cement' },
  { symbol: 'SHRIRAMFIN', name: 'Shriram Finance' },
  { symbol: 'SIEMENS', name: 'Siemens' },
  { symbol: 'SOBHA', name: 'Sobha' },
  { symbol: 'SRF', name: 'SRF' },
  { symbol: 'SUNPHARMA', name: 'Sun Pharmaceutical Industries' },
  { symbol: 'SUNTV', name: 'Sun TV Network' },
  { symbol: 'SUPREMEIND', name: 'Supreme Industries' },
  { symbol: 'SYNGENE', name: 'Syngene International' },
  { symbol: 'TATACOMM', name: 'Tata Communications' },
  { symbol: 'TATACONSUM', name: 'Tata Consumer Products' },
  { symbol: 'TATAELXSI', name: 'Tata Elxsi' },
  { symbol: 'TATAMOTORS', name: 'Tata Motors' },
  { symbol: 'TATAPOWER', name: 'Tata Power' },
  { symbol: 'TATASTEEL', name: 'Tata Steel' },
  { symbol: 'TCS', name: 'Tata Consultancy Services' },
  { symbol: 'TECHM', name: 'Tech Mahindra' },
  { symbol: 'TITAN', name: 'Titan Company' },
  { symbol: 'TORNTPHARM', name: 'Torrent Pharmaceuticals' },
  { symbol: 'TORNTPOWER', name: 'Torrent Power' },
  { symbol: 'TRENT', name: 'Trent' },
  { symbol: 'TRIDENT', name: 'Trident' },
  { symbol: 'UBL', name: 'United Breweries' },
  { symbol: 'UJJIVANSFB', name: 'Ujjivan Small Finance Bank' },
  { symbol: 'ULTRACEMCO', name: 'UltraTech Cement' },
  { symbol: 'UPL', name: 'UPL' },
  { symbol: 'VBL', name: 'Varun Beverages' },
  { symbol: 'VEDL', name: 'Vedanta' },
  { symbol: 'VOLTAS', name: 'Voltas' },
  { symbol: 'WHIRLPOOL', name: 'Whirlpool of India' },
  { symbol: 'WIPRO', name: 'Wipro' },
  { symbol: 'YESBANK', name: 'Yes Bank' },
  { symbol: 'ZEEL', name: 'Zee Entertainment Enterprises' },
  { symbol: 'ZOMATO', name: 'Zomato' },
  { symbol: 'ZYDUSLIFE', name: 'Zydus Lifesciences' },
];

// BSE-specific or BSE-primary stocks
export const BSE_STOCKS: StockEntry[] = [
  { symbol: 'BANKEX', name: 'BSE Bankex Index' },
  { symbol: 'SENSEX', name: 'BSE Sensex Index' },
  // BSE uses same symbols as NSE for most stocks
  ...NSE_STOCKS,
];

export function searchStocks(query: string, exchange: 'NSE' | 'BSE'): StockEntry[] {
  if (!query || query.length < 1) return [];
  const q = query.toUpperCase();
  const list = exchange === 'BSE' ? BSE_STOCKS : NSE_STOCKS;
  return list
    .filter(s =>
      s.symbol.startsWith(q) ||
      s.name.toUpperCase().includes(q) ||
      s.symbol.includes(q)
    )
    .slice(0, 12);
}
